{% set goname = "github.com/golang/dep" %}
{% set version = "0.5.4" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz  # [unix]
    sha256: 929c8f759838f98323211ba408a831ea80d93b75beda8584b6d950f393a3298a  # [unix]
    git_url: https://{{ goname }}  # [win]
    git_tag: v{{ version }}  # [win]

build:
  number: 2
  script:
    - pushd {{ pkg_src }}
    - export GOPATH=$SRC_DIR  # [unix]
    - set GOPATH=%SRC_DIR%  # [win]
    - 'go install -v -ldflags="-X main.version=v{{ version }}" ./cmd/dep'

requirements:
  build:
    - {{ compiler("go") }} >=1.11.3

test:
  requires:         # [win]
    - m2-coreutils  # [win]
  commands:
    - test -x "${PREFIX}/bin/dep"           # [unix]
    - test -x "%PREFIX%\\bin\\dep.exe"        # [win]
    - dep version

about:
  home: https://golang.github.io/dep/
  license: BSD-3-Clause
  license_file: {{ pkg_src }}/LICENSE
  summary: The Go dependency management tool
  doc_url: https://golang.github.io/dep/docs/introduction.html
  dev_url: https://{{ goname }}

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbeda
    - rluria14
    - oblute
