# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "m2iZNtWZlvoHKos8MmaYp4/T0wMrdkVdVIwFBFwekeJKasecrDXDWSVTjgjJU5AZnWwIayPev09jCwyEUSRdhZ5WnUe+CskMbM865YMJbSuCpgPCz40FsK1J8SskECchKDstVzxSmN7AKD4v+59/FGkx+i4vERMmmr7azuUF5AdR8+9e0AwXGGkaHePH1aqXso20k7s4uipapQSNXtqXwwCw+SyJCHtaWtM3O2boYYTRTrgzxpOXU+SyhpyCbXqcBemRLkDoc1trISnCoiZVSVdO156SufXAARXlEdUr4dxn4EFPToIrOnQZUwwZocexJDBeht+2rxck2YqJdXQ3HRtyL2LezGnjBEZpUlN/JNnRhl9OZcJ1n/0PjtmT7HmmIFeeLjYV6EuBILXfBH03jPvJTFt8rgGh0YroZ/qvqrKiIzBEvanMTGzz++qR2AYL464mSH1DBlRkDX7t65NBLEXAJuMhMlH9bKX2F0pJv2zBFveWqQocFdRNOjHs63MXdiGdb3qSpZpJuvJu7oDWOyHWOEARjZU2tNy0R6pGBXitCpPxemHMUqZF9Uly0WNDZV1XjsumtTMVJybBKzDZ6QnYK0ptWi8i83rSBJHqz+Nt8cjTihdw0NH/mRqjQNTV1baRSpW2W39k12uTs6MZqpucQyWroDMzv/efqYW0exA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml